### ISSUE TITLE
How to pull the parameters (mean and standard deviation) of the distribution fitted?

### ISSUE THREAD

**Issue by flippercy** [elephaint/pgbm#3]
Hi:

Thank you for the awesome library! I did some tests with it and have a few questions:

1. How to pull the parameters, such as mean and standard deviation, of the final fitted distribution for each leaf? Such information is extremely helpful when the result is presented and explained to stakeholders. Currently the model just returns some numbers sampled from the distribution but business users are likely to focus on the distribution itself.
 
2. Is there anyway to spit out the model's tree structure to a data frame like what get_dump() does for xgboost?

Thank you!

**Comment by elephaint** [comment]
Hi, 

Thanks for the kind words, much appreciated!

1. That's a good remark, and something I was planning on making available too. It's currently not possible to easily extract those, but it should be an easy fix. I'll have a look at it in the coming days and I expect to make it available either through a separate function or by adding a parameter to the predict / predict_dist functions. 
2. I'm not familiar with the get_dump() from xgboost, but the 'model.save' method saves all the required arrays for the tree. In particular, there are six arrays of importance for the tree structure:

- 'nodes_idx': [n_estimators x max_nodes] int64 array containing indices of nodes. In PGBM, I use a fixed indexing system for node locations in a binary tree. The first (top) node has index one, the first left child node has index two, the first right child node has index three; the left child node of the first left node is four, and so forth. I hope this makes the schema clear. Hence, given any index you can relatively easily understand the position of the node in the binary tree. 
- 'nodes_split_feature': [n_estimators x max_nodes] int64 array. Which feature to split on (i.e. '0'  represents the first feature, and so forth)
- 'nodes_split_bin': [n_estimators x max_nodes] int64 array. Which bin out of the possible max_bins to split on.
- 'leaves_idx': [n_estimators x max_leaves] int64 array. The index of a leaf. Follows the same indexing procedure as desribed above. Index positions are unique, i.e. indices are either nodes or leaves (or non-existent if the tree has stopped learning for some reason before arriving at that index, for example due to hitting the maximum number of leaves)
- 'leaves_mu': [n_estimators x max_leaves] float32 array (float64 in Numba version). The empirical mean ('the leaf weight')
- 'leaves_var': [n_estimators x max_leaves] float32 array (float64 in Numba version). The empirical variance ('the leaf variance').

Note 1) max_nodes = max_leaves - 1
Note 2) For prediction, also the arrays 'bins' ([n_features x n_bins] float32) and the initial prediction (yhat_0, float32 scalar) are required. These are saved too when calling 'model.save'.

Hope this helps! I'll have a look at implementing 1) in the coming days.

Kind regards,

Olivier

**Comment by flippercy** [comment]
@elephaint Thank you for the quick turnaround! Looking forward to the new features in the upgrade.

**Comment by elephaint** [comment]
Hi,

1. This is now available as part of the `predict_dist` function. If you specify `yhat_dist = predict_dist(X_test, output_sample_statistics=True)`, the function will return a tuple (forecasts, mean, variance) with the latter two the learned mean and variance per sample, which can subsequently be used to specify a distribution of your choice. 

Hope this helps, let me know,

Olivier

**Comment by flippercy** [comment]
Thank you Olivier. Appreciate your help!

**Comment by elephaint** [comment]
Great, happy to help!

**Comment by flippercy** [comment]
Hi @elephaint:

Have the upgrades been implemented yet? I've upgraded my library to 1.0 but seen no change.

yhat_dist_pgbm = model.predict_dist(data_val_B_X, n_forecasts=100, output_sample_statistics=True)

_TypeError: predict_dist() got an unexpected keyword argument 'output_sample_statistics'_

print(inspect.getargspec(model.predict_dist))

_ArgSpec(args=['self', 'X', 'n_forecasts', 'parallel'], varargs=None, keywords=None, defaults=(100, True))_

print(PGBM._version)

_1_

Thank you!

**Comment by elephaint** [comment]
Hi, 

How unfortunate, that is very strange. The predict_dist function should support an output_sample_statistics keyword argument. In both the PyTorch and Numba version it is available (I've rechecked the source code and it should be in there...)

If you do `pip list` in the (virtual) Python environment where you installed PGBM, what version of PGBM is listed?

Did you make sure to force the upgrade, for example by doing `pip install pgbm --force-reinstall`?

**Comment by flippercy** [comment]
Thank you for the quick turnaround. That's what I got after running pip install pgbm --force-reinstall :

![image](https://user-images.githubusercontent.com/51969693/130284221-2298aaa3-7139-4e9e-b5ab-45d59081cba6.png)

![image](https://user-images.githubusercontent.com/51969693/130284372-bebc108c-4c8b-42ab-a394-39e370182bee.png)

So it turns out that the new argument is still missing.

**Comment by elephaint** [comment]
Strange and frustrating! I've (i) (re)installed from PyPi in a new virtual environment, (ii) installed on a different pc with a new Python virtual environment, (ii) run in Google Colab and I still can't reproduce the issue. I've tested on Windows 10 (desktop), MacOS (MacBook Pro) and Linux (Colab), and for both Numba and Torch versions.

Can you run [this example](https://github.com/elephaint/pgbm/blob/main/examples/pytorch/example01_bostonhousing_cpu.ipynb) in Google Colab? In that example, you should be able to call the `predict_dist` function with the `output_sample_statistics` argument, i.e. `output = model.predict_dist(X, output_sample_statistics=True)`

I'm trying to think of what could go wrong... are you certain `!pip list` is executed from the same (virtual) environment as in which you execute PGBM? What kind of (Python) setup are you running? It feels as if there is a cached version somewhere left in the environment that apparently the code calls when executing the `inspect` calls.

**Comment by flippercy** [comment]
It is weird. I reinstalled JupyterHub on my linux server and it works now. Not sure what happened.

Thank you very much for your help!

**Comment by elephaint** [comment]
Great! Python's package manager is a mystery sometimes....
